name: Matrix Build Pattern 1
on:
  push:
    branches:
      - test-matrix

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016, windows-2019]
        platform: [x32, x64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build Project
        run: |
          echo "Build on ${{ matrix.os }}-${{ matrix.platform }}"
