name: Dump Env Variables
on:
  push:
    branches:
      - test-env-context

jobs:
  dump-env:
    runs-on: ubuntu-16.04
    steps:
      - name: Default Env Variables
        run: |
          echo "GITHUB_WORKFLOW ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION ${GITHUB_ACTION}"
          echo "GITHUB_ACTOR ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH ${GITHUB_EVENT_PATH}"
          echo "GITHUB_WORKSPACE ${GITHUB_WORKSPACE}"
          echo "GITHUB_REF ${GITHUB_REF}"
          echo "GITHUB_SHA ${GITHUB_SHA}"
